### ISSUE TITLE
能否支持宽屏模式

### ISSUE THREAD

**Issue by jayazhao** [WizTeam/WizNoteLite#100]
以我个人的偏好来说,目前全屏模式下的编辑器宽度还是感觉略窄了，尤其是台式机子上，左右很大一块是空白的，能否支持宽屏模式，或者是自定义设置编辑器宽度占屏幕的百分比呢？

**Comment by jxiaow** [comment]
#96 根据上述方法，可以在cutsom.css 中添加 如下内容即可扩展宽屏：
```css
.jss118 {
    padding-left: max(44px, (100% - 900px) / 2 - 40px) !important;
    padding-right: max(44px, (100% - 900px) / 2 - 40px) !important;
}

div[id^=ag-editor-id]>.ag-paragraph {
    margin-bottom: 5px;
    margin-top: 10px;
}
```
@jayazhao
