### ISSUE TITLE
用户自定义样式

### ISSUE THREAD

**Issue by NoverNobida** [WizTeam/WizNoteLite#96]
软件本身是做记录而不是展示，但是目前遇到的问题是各级标题字体过大，段间距过大的问题，同时，行间代码块上下实际上分别有一行
\```
占用一行的位置，焦点不在这个代码块的时候，实际上这个代码块上下都多出一行空白。因此总体来说，笔记会因为较大的标题字体、行距、较多的空白等等而显得松散，内容不紧凑，这样可能看（展示）起来比较美观，但是实际上一个画面不能容纳较多内容，不利于笔记的记录和阅读。
但是这可能仅仅是个人习惯或审美，本来可以自己更改，但是一方面更改麻烦，另一方面更改后升级或重装又会还原。因此，可否考虑用户自行添加CSS样式，保存为一个类似于 `custom.css` 的文件，在使用时加载并且优先级高于本身样式？升级时得以保留，新安装时可以快速复制粘贴来添加，甚至可以将其纳入同步内容，在各桌面端得以同步。

**Comment by wanniwa** [comment]
没想到和我有同样想法的，我也是觉得上下间距有点过大了，写的没有一种充实感，所以还是用回了为知本体。

**Comment by NoverNobida** [comment]
我目前有方法：
1. 点击wiznote lite的开发者模式，找到相应元素的CSS样式，调节为自己喜欢的样式，例如减小各级标题大小以及上下间距
```css
.editor-container div[id^=editor_] .vditor-reset>h2 {
    font-size: 24px;
    margin: 12px 0 10px;
}
.editor-container div[id^=editor_] .vditor-reset>h3 {
    font-size: 22px;
    margin: 12px 0 10px;
}
......
```
2. 在任意位置保存为一个CSS文件，例如`custum.css`，记录路径。
3. 打开 `\安装目录\WizNote Lite\resources\app\web-app` ，编辑 `index.html` ，在 `head` 的最后（也就是 `</head>` 前面）添加一行 `<link rel="stylesheet" href="\样式文件保存路径\custom.css">` ，保存，彻底结束wiznote lite进程（因为关闭了窗口仍然会后台运行），重启即可。
4. 每次更新后只需要更改这一个文件，只要添加一行，除非更新中把元素名称更改了。

**Comment by NoverNobida** [comment]
> 没想到和我有同样想法的，我也是觉得上下间距有点过大了，写的没有一种充实感，所以还是用回了为知本体。

 我目前有方法：
1. 点击wiznote lite的开发者模式，找到相应元素的CSS样式，调节为自己喜欢的样式，例如减小各级标题大小以及上下间距
```css
.editor-container div[id^=editor_] .vditor-reset>h2 {
    font-size: 24px;
    margin: 12px 0 10px;
}
.editor-container div[id^=editor_] .vditor-reset>h3 {
    font-size: 22px;
    margin: 12px 0 10px;
}
......
```
2. 在任意位置保存为一个CSS文件，例如`custum.css`，记录路径。
3. 打开 `\安装目录\WizNote Lite\resources\app\web-app` ，编辑 `index.html` ，在 `head` 的最后（也就是 `</head>` 前面）添加一行 `<link rel="stylesheet" href="\样式文件保存路径\custom.css">` ，保存，彻底结束wiznote lite进程（因为关闭了窗口仍然会后台运行），重启即可。
4. 每次更新后只需要更改这一个文件，只要添加一行，除非更新中把元素名称更改了。
